# License
#
# Copyright (C) 2020 Dror Smolarsky
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Code samples on using std::all_of algorithm
"""

load("//bazel:cc.bzl", "xkv_cc_library")

xkv_cc_library(
    name = "util",
    srcs = glob([
        "src/*.cc",
        "src/*.h",
    ]),
    hdrs = glob(["include/**/*.h"]),
    version = "0.0.0",
    visibility = ["//visibility:public"],
)
